class Emoji {
  constructor(simbolo) {
    this.simbolo = simbolo;
  }
}

const emojis = [
  new Emoji("🩷"),
  new Emoji("🤎"),
  new Emoji("🩶"),
  new Emoji("🖤"),
  new Emoji("🤍"),
  new Emoji("💙"),
  new Emoji("💜"),
  new Emoji("💚"),
  new Emoji("❤️"),
  new Emoji("❤️‍🩹"),
  new Emoji("🧡"),
  new Emoji("💛"),
  new Emoji("🦷"),
  new Emoji("🧠"),
  new Emoji("🐸"),
  new Emoji("🐵"),
  new Emoji("🍙"),
  new Emoji("🍘"),
  new Emoji("⚽"),
  new Emoji("🌚"),
  new Emoji("⛔"),
  new Emoji("🏳️‍⚧️"),
  new Emoji("🏴‍☠️"),
  new Emoji("🏳️‍🌈"),
  new Emoji("🏁"),
  new Emoji("🅰️"),
  new Emoji("☢️"),
  new Emoji("💽"),
  new Emoji("☀️"),
  new Emoji("🏯"),
  new Emoji("🛞"),
  new Emoji("🥎"),
  new Emoji("🥮"),
  new Emoji("😡"),
  new Emoji("🤡"),
  new Emoji("👁️"),
  new Emoji("🫁"),
  new Emoji("👹"),
  new Emoji("❤️‍🔥"),
  new Emoji("💌"),
  new Emoji("🎁"),
  new Emoji("🚀"),
  new Emoji("🥌"),
  new Emoji("🎮"),
  new Emoji("🧱"),
  new Emoji("🌎"),
  new Emoji("🪪"),
  new Emoji("🪓"),
  new Emoji("🅱️"),
  new Emoji("🏀"),
];  